### ISSUE TITLE
cam_K

### ISSUE THREAD

**Issue by JiageWang** [yinyunie/Total3DUnderstanding#9]
I don't understand what the matrix in "cam_K.txt" represents. If I want to use my own picture, how can I get this matrix? Thanks.

**Comment by yinyunie** [comment]
Hi, 

Its the camera intrinsic matrix.

Since our model is trained on SUN RGB-D dataset (with common RGB-D scanners), we recommend you to retrain the model on your own datasets before using it. If you just want to have a running test. We did not have such a try but recommend you to 1. simply process your image making it to the same scale of the SUN-RGBD images and try our cam_k. **OR** 2. seriously calibrate your camera intrinsic parameters.
